services:
  app:
    #image: ghcr.io/dead-antler/burberry:latest
    image: localhost/burberry:latest
    ports:
      - "3000:3000"
    environment:
      PUID: ${PUID:-1001}
      PGID: ${PGID:-1001}
      DB_FILE_NAME: file:data/database.db
      AUTH_SECRET: ${AUTH_SECRET:?Set AUTH_SECRET in .env or environment}
      AUTH_URL: ${AUTH_URL:-http://localhost:3000}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      # ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
    volumes:
      - app-data:/app/data
    restart: unless-stopped

volumes:
  app-data:
